# Generated by Django 3.0.3 on 2020-02-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
